"""adicionado nullable false.

Revision ID: 6cb3b881232f
Revises: 1d0be2546a9d
Create Date: 2024-09-15 15:18:07.884615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb3b881232f'
down_revision = '1d0be2546a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alugueis', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alugueis', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
